import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PdfSection {
  title: string;
  rows?: Array<[string, string]>;
  body?: string[];
}

export function exportGovernedPdf(title: string, subtitle: string, sections: PdfSection[], filename: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 42;
  let y = 54;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(title, margin, y);
  y += 22;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(subtitle, margin, y);
  y += 24;

  for (const section of sections) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(section.title, margin, y);
    y += 12;
    if (section.body?.length) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      for (const paragraph of section.body) {
        const lines = doc.splitTextToSize(paragraph, 510);
        if (y + lines.length * 12 > 790) { doc.addPage(); y = 50; }
        doc.text(lines, margin, y);
        y += lines.length * 12 + 6;
      }
    }
    if (section.rows?.length) {
      autoTable(doc, {
        startY: y,
        body: section.rows,
        theme: 'grid',
        styles: { fontSize: 8, cellPadding: 5 },
        margin: { left: margin, right: margin },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 150 } },
      });
      y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y) + 18;
    }
    if (y > 760) { doc.addPage(); y = 50; }
  }

  doc.setFontSize(7);
  doc.setTextColor(90);
  doc.text(`Generated by Kairon cockpit · ${new Date().toISOString()} · configuration is not execution`, margin, 815);
  doc.save(filename);
}
