export interface PdfSection {
  title: string;
  rows?: Array<[string, string]>;
  body?: string[];
}

function esc(value: string) {
  return value.replace(/[&<>"']/g, (ch) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[ch] ?? ch));
}

export function exportGovernedPdf(title: string, subtitle: string, sections: PdfSection[], filename: string) {
  if (typeof window === 'undefined') return;
  const sectionHtml = sections.map((section) => {
    const body = (section.body ?? []).map((p) => `<p>${esc(p)}</p>`).join('');
    const rows = section.rows?.length
      ? `<table>${section.rows.map(([k,v]) => `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</table>`
      : '';
    return `<section><h2>${esc(section.title)}</h2>${body}${rows}</section>`;
  }).join('');
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
    @page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#20231f;font-size:10pt;line-height:1.45}h1{font-family:Georgia,serif;font-weight:500;font-size:23pt;margin:0 0 4mm}h2{font-size:11pt;margin:8mm 0 3mm}p{margin:0 0 3mm}table{width:100%;border-collapse:collapse;margin:2mm 0 5mm}th,td{border:1px solid #d8d1c3;padding:2.3mm;text-align:left;vertical-align:top}th{width:32%;background:#f2eee5}.meta{color:#6f7068;font-size:8pt;margin-bottom:9mm}.foot{margin-top:12mm;padding-top:3mm;border-top:1px solid #d8d1c3;color:#777;font-size:7pt}section{break-inside:avoid}
  </style></head><body><h1>${esc(title)}</h1><div class="meta">${esc(subtitle)}</div>${sectionHtml}<div class="foot">Generated by Kairon cockpit · ${new Date().toISOString()} · configuration is not execution · suggested filename: ${esc(filename)}</div><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),120));<\/script></body></html>`;
  const printWindow = window.open('', '_blank', 'noopener,noreferrer');
  if (!printWindow) return;
  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}
